services:

  frontend:
    build: ../apps/frontend
    container_name: frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

  backend:
    build: ../apps/backend
    container_name: backend

    ports:
      - "8000:8000"
